name: Deploy static HTML to Azure Web App - MYAPP01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write       # Required for Azure OIDC login
      contents: read        # Required to checkout repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static HTML files from APP folder
        run: |
          mkdir site
          copy APP\* site\   # Copy files from APP folder to site folder
          powershell Compress-Archive -Path site\* -DestinationPath site.zip

      - name: List files in current directory (debug step)
        run: dir

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: eb1dfb73-6f48-4952-bc18-db0d50083a6c
          tenant-id: bf7f6c35-a901-4467-b2ac-46fff520f3fa
          subscription-id: 61c93cef-3378-4258-b3f6-98ce21be82e9

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MYAPP01'
          slot-name: 'Production'
          package: './site.zip'
