name: Deploy static HTML to Azure Web App - MYAPP01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write       # Required for Azure OIDC login
      contents: read        # Required to checkout repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Create site folder and copy necessary files
      - name: Prepare site content
        run: |
          mkdir site
          copy APP site\
          copy index.html site\

      # Step 2: Create ZIP archive from the site folder
      - name: Create site.zip
        run: powershell Compress-Archive -Path site\* -DestinationPath site.zip

      # Optional Debug: List contents of the ZIP
      - name: Verify site.zip contents
        run: |
          powershell Expand-Archive -Path site.zip -DestinationPath test
          dir test

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: eb1dfb73-6f48-4952-bc18-db0d50083a6c
          tenant-id: bf7f6c35-a901-4467-b2ac-46fff520f3fa
          subscription-id: 61c93cef-3378-4258-b3f6-98ce21be82e9

      # Step 4: Deploy the zip file to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MYAPP01'
          slot-name: 'Production'
          package: './site.zip'
