name: Build and Deploy ASP.NET Core App to Azure Web App - MYAPP-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Stable version

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish /p:PublishTrimmed=false

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Zip the package
        run: Compress-Archive -Path .\app\* -DestinationPath app.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: eb1dfb73-6f48-4952-bc18-db0d50083a6c
          tenant-id: bf7f6c35-a901-4467-b2ac-46fff520f3fa
          subscription-id: 61c93cef-3378-4258-b3f6-98ce21be82e9

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MYAPP01'
          slot-name: 'Production'
          package: app.zip
